name = "mh-construction-website"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production]
name = "mh-construction-prod"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
zone_id = "YOUR_CLOUDFLARE_ZONE_ID"

[env.staging]
name = "mh-construction-staging"
account_id = "YOUR_CLOUDFLARE_ACCOUNT_ID"
zone_id = "YOUR_CLOUDFLARE_ZONE_ID"

# Custom domain configuration
route = "mhconstruction.com/*"

# Environment variables
[vars]
ENVIRONMENT = "production"
API_BASE_URL = "https://api.mhconstruction.com"

# KV Namespaces for caching
[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Security headers
[wrangler]
send_metrics = false

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Rules configuration
[rules]
# Security rule for admin paths
[[rules]]
type = "redirect"
from = "/admin/*"
to = "/login"
status = 302