import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "Enlist → Careers | Build More Than Projects - Build Your Future | MH Construction",
  description:
    "Enlist → Careers: Build More Than Projects - Build Your Future with a Veteran-Owned Team. Join the mission - your construction career starts here. Explore career opportunities at MH Construction. Join our veteran-led team in the Tri-Cities with service-earned values. We offer competitive benefits, professional development, transparent expectations, proven mentorship, and a collaborative work environment where military precision meets construction excellence.",
  keywords: [
    "Enlist Careers build your future",
    "join the mission construction career",
    "veteran-owned construction careers",
    "service-earned career values",
    "dual-label career opportunities",
    "military precision construction jobs",
    "construction jobs",
    "construction careers",
    "veteran employment",
    "construction job openings",
    "Project Manager jobs",
    "Superintendent jobs",
    "Carpenter jobs",
    "Project Engineer jobs",
    "Admin Assistant jobs",
    "construction Project Manager",
    "construction Superintendent",
    "construction Carpenter",
    "construction Project Engineer",
    "construction Admin Assistant",
    "Project Manager Tri-Cities",
    "Superintendent Tri-Cities",
    "Carpenter Tri-Cities",
    "Project Engineer Tri-Cities",
    "Admin Assistant Tri-Cities",
    "Tri-Cities construction jobs",
    "Richland construction jobs",
    "Pasco construction careers",
    "Kennewick construction employment",
    "Benton County construction jobs",
    "Franklin County construction careers",
    "general contractor jobs Tri-Cities",
    "join construction team",
    "construction employment",
    "contractor careers",
    "veteran-friendly employer",
    "construction opportunities",
  ],
  openGraph: {
    title: "Enlist → Careers | Build Your Future - MH Construction",
    description:
      "Enlist → Careers: Build More Than Projects - Build Your Future. Join the mission with a veteran-led construction team. Service-earned values, competitive benefits, transparent expectations, and proven mentorship in the Tri-Cities.",
    type: "website",
    locale: "en_US",
    url: "https://www.mhc-gc.com/careers",
    siteName: "MH Construction",
  },
  twitter: {
    card: "summary",
    site: "@mhc_gc",
    creator: "@mhc_gc",
    title: "Enlist → Careers | Build Your Future - MH Construction",
    description:
      "Join the mission: Build More Than Projects - Build Your Future. Veteran-led team with service-earned values. Competitive benefits, proven mentorship, military precision meets construction excellence.",
  },
  alternates: {
    canonical: "https://www.mhc-gc.com/careers",
  },
  robots: {
    index: true,
    follow: true,
  },
};
