import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Careers - Join Our Veteran-Led Construction Team | MH Construction",
  description:
    "Explore career opportunities at MH Construction. Join our veteran-led team in the Tri-Cities. We offer competitive benefits, professional development, and a collaborative work environment.",
  keywords: [
    "construction jobs",
    "construction careers",
    "veteran employment",
    "construction job openings",
    "Project Manager jobs",
    "Superintendent jobs",
    "Carpenter jobs",
    "Project Engineer jobs",
    "Admin Assistant jobs",
    "construction Project Manager",
    "construction Superintendent",
    "construction Carpenter",
    "construction Project Engineer",
    "construction Admin Assistant",
    "Project Manager Tri-Cities",
    "Superintendent Tri-Cities",
    "Carpenter Tri-Cities",
    "Project Engineer Tri-Cities",
    "Admin Assistant Tri-Cities",
    "Tri-Cities construction jobs",
    "Richland construction jobs",
    "Pasco construction careers",
    "Kennewick construction employment",
    "Benton County construction jobs",
    "Franklin County construction careers",
    "general contractor jobs Tri-Cities",
    "join construction team",
    "construction employment",
    "contractor careers",
    "veteran-friendly employer",
    "construction opportunities",
  ],
  openGraph: {
    title: "Careers at MH Construction",
    description:
      "Join our veteran-led construction team in the Tri-Cities. Competitive benefits and professional growth opportunities available.",
    type: "website",
    url: "https://www.mhc-gc.com/careers",
  },
  alternates: {
    canonical: "https://www.mhc-gc.com/careers",
  },
};
