#!/bin/bash

# Emoji replacement script for militaryConstructionAI.ts
FILE="/workspaces/mh-website/src/lib/militaryConstructionAI.ts"

# Create a backup first
cp "$FILE" "${FILE}.backup"

# Replace emojis with Material Icon text labels
sed -i 's/✅/[CHECK_CIRCLE]/g' "$FILE"
sed -i 's/⚠️/[WARNING]/g' "$FILE"
sed -i 's/🎖️/[MILITARY_TECH]/g' "$FILE"
sed -i 's/🎯/[GPS_FIXED]/g' "$FILE"
sed -i 's/📋/[ASSIGNMENT]/g' "$FILE"
sed -i 's/📞/[PHONE]/g' "$FILE"
sed -i 's/🔴/[ERROR]/g' "$FILE"
sed -i 's/💰/[ATTACH_MONEY]/g' "$FILE"
sed -i 's/⚡/[BOLT]/g' "$FILE"
sed -i 's/🚀/[ROCKET_LAUNCH]/g' "$FILE"
sed -i 's/📅/[EVENT]/g' "$FILE"
sed -i 's/🏠/[HOME]/g' "$FILE"
sed -i 's/🇺🇸/[FLAG]/g' "$FILE"
sed -i 's/🔧/[BUILD]/g' "$FILE"
sed -i 's/📍/[LOCATION_ON]/g' "$FILE"
sed -i 's/🚨/[EMERGENCY]/g' "$FILE"
sed -i 's/🔥/[WHATSHOT]/g' "$FILE"
sed -i 's/📧/[EMAIL]/g' "$FILE"
sed -i 's/📝/[EDIT_NOTE]/g' "$FILE"
sed -i 's/🏗️/[CONSTRUCTION]/g' "$FILE"
sed -i 's/🌡️/[THERMOSTAT]/g' "$FILE"
sed -i 's/❄️/[AC_UNIT]/g' "$FILE"
sed -i 's/🦅/[SPA]/g' "$FILE"
sed -i 's/🟢/[CHECK_CIRCLE]/g' "$FILE"
sed -i 's/🟡/[PRIORITY_HIGH]/g' "$FILE"
sed -i 's/🛟/[SAFETY_RING]/g' "$FILE"
sed -i 's/📊/[ANALYTICS]/g' "$FILE"
sed -i 's/👨‍💼/[PERSON]/g' "$FILE"
sed -i 's/👥/[GROUPS]/g' "$FILE"
sed -i 's/🏛️/[ACCOUNT_BALANCE]/g' "$FILE"
sed -i 's/❓/[HELP]/g' "$FILE"
sed -i 's/✈️/[FLIGHT]/g' "$FILE"
sed -i 's/⚓/[ANCHOR]/g' "$FILE"
sed -i 's/♿/[ACCESSIBLE]/g' "$FILE"
sed -i 's/⏰/[ALARM]/g' "$FILE"
sed -i 's/🛡️/[SECURITY]/g' "$FILE"
sed -i 's/🔵/[INFO]/g' "$FILE"
sed -i 's/🔒/[LOCK]/g' "$FILE"
sed -i 's/🔍/[SEARCH]/g' "$FILE"
sed -i 's/🔄/[REFRESH]/g' "$FILE"
sed -i 's/📸/[PHOTO_CAMERA]/g' "$FILE"
sed -i 's/📱/[SMARTPHONE]/g' "$FILE"
sed -i 's/📡/[SIGNAL_CELLULAR_ALT]/g' "$FILE"
sed -i 's/💼/[WORK]/g' "$FILE"
sed -i 's/💵/[PAYMENTS]/g' "$FILE"
sed -i 's/💲/[MONETIZATION_ON]/g' "$FILE"
sed -i 's/💡/[LIGHTBULB]/g' "$FILE"
sed -i 's/💎/[DIAMOND]/g' "$FILE"
sed -i 's/👨‍⚕️/[MEDICAL_SERVICES]/g' "$FILE"
sed -i 's/ℹ️/[INFO]/g' "$FILE"
sed -i 's/🚢/[DIRECTIONS_BOAT]/g' "$FILE"
sed -i 's/⏱️/[TIMER]/g' "$FILE"
sed -i 's/🗺️/[MAP]/g' "$FILE"
sed -i 's/📦/[INVENTORY_2]/g' "$FILE"

echo "Emoji replacement completed for militaryConstructionAI.ts"
echo "Backup saved as ${FILE}.backup"