#!/bin/bash
# Auto-generated naming standardization script
# Generated on Wed Oct  8 16:40:48 UTC 2025

mv "docs/project/SERVICE" "CARDS-VISUAL-GUIDE.md -> docs/project/SERVICE_CARDS_VISUAL_GUIDE.md"
mv "docs/project/archive/design" "updates/SHIMMER-REMOVAL-SUMMARY.md -> docs/project/archive/design-updates/SHIMMER_REMOVAL_SUMMARY.md"
mv "docs/project/archive/design" "updates/FOOTER-ENHANCEMENT-SUMMARY.md -> docs/project/archive/design-updates/FOOTER_ENHANCEMENT_SUMMARY.md"
mv "docs/project/archive/design" "updates/HEADER-BUBBLE-CLEANUP-SUMMARY.md -> docs/project/archive/design-updates/HEADER_BUBBLE_CLEANUP_SUMMARY.md"
mv "docs/project/archive/design" "updates/CTA-SECTION-REMOVAL-SUMMARY.md -> docs/project/archive/design-updates/CTA_SECTION_REMOVAL_SUMMARY.md"
mv "docs/project/archive/design" "updates/SOCIAL-MEDIA-UPDATE-SUMMARY.md -> docs/project/archive/design-updates/SOCIAL_MEDIA_UPDATE_SUMMARY.md"
mv "docs/project/archive/design" "updates/CORE-VALUES-UPDATE-SUMMARY.md -> docs/project/archive/design-updates/CORE_VALUES_UPDATE_SUMMARY.md"
mv "docs/project/archive/implementation" "fixes/ICON-SYSTEM-UPDATE-SUMMARY.md -> docs/project/archive/implementation-fixes/ICON_SYSTEM_UPDATE_SUMMARY.md"
mv "docs/project/archive/implementation" "fixes/ICON-SIZE-FIX-SUMMARY.md -> docs/project/archive/implementation-fixes/ICON_SIZE_FIX_SUMMARY.md"
mv "docs/project/archive/implementation" "fixes/ICON-CSS-TAILWIND-OPTIMIZATION-SUMMARY.md -> docs/project/archive/implementation-fixes/ICON_CSS_TAILWIND_OPTIMIZATION_SUMMARY.md"
mv "docs/project/archive/implementation" "fixes/SERVICE-CARDS-LAYOUT-FIX.md -> docs/project/archive/implementation-fixes/SERVICE_CARDS_LAYOUT_FIX.md"
mv "docs/project/archive/implementation" "fixes/ICON-SPACE-MAXIMIZATION-SUMMARY.md -> docs/project/archive/implementation-fixes/ICON_SPACE_MAXIMIZATION_SUMMARY.md"
mv "docs/FIREBASE" "SETUP.md -> docs/FIREBASE_SETUP.md"
mv "docs/reference/ICON" "SIZE-TROUBLESHOOTING.md -> docs/reference/ICON_SIZE_TROUBLESHOOTING.md"
mv "docs/technical/ICON" "SYSTEM-QUICK-REFERENCE.md -> docs/technical/ICON_SYSTEM_QUICK_REFERENCE.md"
mv "docs/business/MH" "BRANDING.md -> docs/business/MH_BRANDING.md"
mv "docs/business/team" "profiles/brittney-holstein.md -> docs/business/team-profiles/BRITTNEY_HOLSTEIN.md"
mv "docs/business/team" "profiles/derek-parks.md -> docs/business/team-profiles/DEREK_PARKS.md"
mv "docs/business/team" "profiles/reagan-massey.md -> docs/business/team-profiles/REAGAN_MASSEY.md"
mv "docs/business/team" "profiles/steve-mcclary.md -> docs/business/team-profiles/STEVE_MCCLARY.md"
mv "docs/business/team" "profiles/ronaldo-garcia.md -> docs/business/team-profiles/RONALDO_GARCIA.md"
mv "docs/business/team" "profiles/lisa-kandle.md -> docs/business/team-profiles/LISA_KANDLE.md"
mv "docs/business/team" "profiles/jeremy-thamert.md -> docs/business/team-profiles/JEREMY_THAMERT.md"
mv "docs/business/team" "profiles/lisa.md -> docs/business/team-profiles/LISA.md"
mv "docs/business/team" "profiles/arnold-garcia.md -> docs/business/team-profiles/ARNOLD_GARCIA.md"
mv "docs/business/team" "profiles/mike-holstein.md -> docs/business/team-profiles/MIKE_HOLSTEIN.md"
mv "docs/business/team" "profiles/todd-schoeff.md -> docs/business/team-profiles/TODD_SCHOEFF.md"
mv "docs/business/team" "profiles/matt-ramsey.md -> docs/business/team-profiles/MATT_RAMSEY.md"
mv "docs/business/team" "profiles/makayla-holstein.md -> docs/business/team-profiles/MAKAYLA_HOLSTEIN.md"
mv "docs/business/team" "profiles/porter-cline.md -> docs/business/team-profiles/PORTER_CLINE.md"
mv "docs/business/team" "profiles/ben-woodall.md -> docs/business/team-profiles/BEN_WOODALL.md"
mv "docs/business/team" "profiles/brooks-morris.md -> docs/business/team-profiles/BROOKS_MORRIS.md"
mv "docs/business/team" "profiles/jennifer-tenehuerta.md -> docs/business/team-profiles/JENNIFER_TENEHUERTA.md"
mv "docs/business/team" "profiles/trigger.md -> docs/business/team-profiles/TRIGGER.md"
