// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - .open-next/worker.js is generated by opennextjs-cloudflare build and does not exist until after the build step runs.
import openNextWorker from "./.open-next/worker.js";

export default {
  fetch: openNextWorker.fetch,
};
